package com.volume_plus_plus.app.ui.theme

import androidx.compose.ui.graphics.Color

// Fallback palette for devices without dynamic color (pre-Android 12), generated from seed
// #475D91 — a muted signal-indigo that sits close to what Material You produces on blue
// wallpapers, so the fallback doesn't read as a different app.

// Light
val PrimaryLight = Color(0xFF475D91)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFD9E2FF)
val OnPrimaryContainerLight = Color(0xFF001945)
val SecondaryLight = Color(0xFF575E71)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFDBE2F9)
val OnSecondaryContainerLight = Color(0xFF141B2C)
val TertiaryLight = Color(0xFF715573)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFBD7FB)
val OnTertiaryContainerLight = Color(0xFF29132D)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFAF9FF)
val OnBackgroundLight = Color(0xFF1A1B20)
val SurfaceLight = Color(0xFFFAF9FF)
val OnSurfaceLight = Color(0xFF1A1B20)
val SurfaceVariantLight = Color(0xFFE1E2EC)
val OnSurfaceVariantLight = Color(0xFF44464F)
val OutlineLight = Color(0xFF757780)
val OutlineVariantLight = Color(0xFFC5C6D0)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF4F3FA)
val SurfaceContainerLight = Color(0xFFEEEDF4)
val SurfaceContainerHighLight = Color(0xFFE8E7EF)
val SurfaceContainerHighestLight = Color(0xFFE2E2E9)
val InversePrimaryLight = Color(0xFFB0C6FF)
val InverseSurfaceLight = Color(0xFF2F3036)
val InverseOnSurfaceLight = Color(0xFFF1F0F7)

// Dark
val PrimaryDark = Color(0xFFB0C6FF)
val OnPrimaryDark = Color(0xFF152E60)
val PrimaryContainerDark = Color(0xFF2F4578)
val OnPrimaryContainerDark = Color(0xFFD9E2FF)
val SecondaryDark = Color(0xFFBFC6DC)
val OnSecondaryDark = Color(0xFF293041)
val SecondaryContainerDark = Color(0xFF3F4759)
val OnSecondaryContainerDark = Color(0xFFDBE2F9)
val TertiaryDark = Color(0xFFDFBBDE)
val OnTertiaryDark = Color(0xFF402843)
val TertiaryContainerDark = Color(0xFF583E5B)
val OnTertiaryContainerDark = Color(0xFFFBD7FB)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF121318)
val OnBackgroundDark = Color(0xFFE2E2E9)
val SurfaceDark = Color(0xFF121318)
val OnSurfaceDark = Color(0xFFE2E2E9)
val SurfaceVariantDark = Color(0xFF44464F)
val OnSurfaceVariantDark = Color(0xFFC5C6D0)
val OutlineDark = Color(0xFF8F9099)
val OutlineVariantDark = Color(0xFF44464F)
val SurfaceContainerLowestDark = Color(0xFF0C0E13)
val SurfaceContainerLowDark = Color(0xFF1A1B20)
val SurfaceContainerDark = Color(0xFF1E1F25)
val SurfaceContainerHighDark = Color(0xFF282A2F)
val SurfaceContainerHighestDark = Color(0xFF33343A)
val InversePrimaryDark = Color(0xFF475D91)
val InverseSurfaceDark = Color(0xFFE2E2E9)
val InverseOnSurfaceDark = Color(0xFF2F3036)
